import { NavBar } from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <NavBar />
        <div className='px-4 py-8 bg-gradient-to-br from-zinc-100'>
          <div className='max-w-7xl m-auto'>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
